### PR TITLE
health check fixes

### PR DESCRIPTION
**Pull request by monosoul**
1. Changes Kafka health checks to use interfaces instead of implementations: e960d7aec6ad087647d45d8fb9b632875691c2a2
2. Makes it possible to register multiple health checks of the same type by providing different names: 0d0c4b3c2a3bca2c7d296c428123b1b13d258809 . This is useful when you have multiple consumers within the same app.
3. fixes `DatabaseConnectionHealthCheck` so that it returns `Unhealthy` if connection is invalid: e4ec143ef1e4014ae096438dbef5ca7490818040
4. introduces `GenericMongoConnectionHealthCheck` that can be used with both sync and async clients, also changes the dependency config there so that it doesn't bring `sync` client as a transitive dependency to projects using it: 86c566e021f127a2fce7d6b7fd2f89399bfde51e

### CODE REVIEW

**Comment by monosoul** [comment]
@sksamuel  would it be okay if I update all healthchecks to have name as a constructor argument? I realized in some apps we have multiple datasources, so registering multiple DB healthchecks would also be handy.

**Comment by sksamuel** [comment]
Yep that works.

**Comment by sksamuel** [comment]
Do you want to do that in this PR or as a follow on ?

**Comment by monosoul** [comment]
@sksamuel did it all in this PR. I've also fixed `DatabaseConnectionHealthCheck` since it was previously ignoring `isValid` call result and made `cohort-mongo` module usable with both `sync` and `async` clients (I kept the original `MongoConnectionHealthCheck` there for backwards compatibility)

**Review by sksamuel — APPROVED** [review]

**Comment by sksamuel** [comment]
Niceeee

**Comment by monosoul** [comment]
@sksamuel any chance you could release it this week? :innocent:

**Comment by sksamuel** [comment]
2.3.1 is out :)

**Comment by monosoul** [comment]
Btw, @sksamuel you didn't create a release in GH. Not sure if that's a big problem, but I imagine might be confusing to people

**Comment by sksamuel** [comment]
Oops. I did now.

**Pull request merged**
